services:
  postgres:
    image: postgres:16
    container_name: cronas-postgres
    environment:
      POSTGRES_DB: cronas
      POSTGRES_USER: cronas
      POSTGRES_PASSWORD: cronas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cronas-redis
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.2.0
    container_name: cronas-kafka
    ports:
      - "9092:9092"

volumes:
  postgres_data:
