from __future__ import annotations

import argparse
from pathlib import Path


API_MAIN = """from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Distributed Task Scheduler API")


class JobCreate(BaseModel):
    name: str
    schedule_type: str
    payload: dict
    scheduled_at: str | None = None
    cron: str | None = None


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/jobs")
def create_job(job: JobCreate) -> dict[str, object]:
    return {"message": "Implement persistence and enqueue logic", "job": job.model_dump()}
"""


WATCHER_MAIN = """import time


POLL_SECONDS = 20


def poll_due_jobs() -> None:
    # Replace with Redis sorted-set polling and Kafka publish logic.
    print("Polling Redis for due jobs...")


def main() -> None:
    while True:
        poll_due_jobs()
        time.sleep(POLL_SECONDS)


if __name__ == "__main__":
    main()
"""


EXECUTOR_MAIN = """def handle_message(message: dict) -> None:
    # Replace with business execution, idempotency, and status updates.
    print(f"Executing job: {message}")


def main() -> None:
    # Replace with Kafka consumer startup and loop.
    print("Start Kafka consumer here")


if __name__ == "__main__":
    main()
"""


REQUIREMENTS = """fastapi
uvicorn
pydantic
redis
kafka-python
psycopg[binary]
"""


README = """Starter generated by the distributed-task-scheduler skill.

Next steps:
- wire configuration through environment variables
- connect PostgreSQL, Redis, and Kafka
- add logging, tracing, and tests
- implement durable job state updates
"""


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def scaffold_api(output: Path) -> None:
    write_file(output / "app" / "main.py", API_MAIN)
    write_file(output / "requirements.txt", REQUIREMENTS)
    write_file(output / "README.md", README)


def scaffold_watcher(output: Path) -> None:
    write_file(output / "watcher.py", WATCHER_MAIN)
    write_file(output / "requirements.txt", REQUIREMENTS)
    write_file(output / "README.md", README)


def scaffold_executor(output: Path) -> None:
    write_file(output / "executor.py", EXECUTOR_MAIN)
    write_file(output / "requirements.txt", REQUIREMENTS)
    write_file(output / "README.md", README)


def main() -> None:
    parser = argparse.ArgumentParser(description="Scaffold a starter service for the distributed task scheduler project.")
    parser.add_argument("--kind", choices=["api", "watcher", "executor"], required=True)
    parser.add_argument("--output", required=True, help="Output directory for the generated service")
    args = parser.parse_args()

    output = Path(args.output).resolve()
    output.mkdir(parents=True, exist_ok=True)

    if args.kind == "api":
        scaffold_api(output)
    elif args.kind == "watcher":
        scaffold_watcher(output)
    else:
        scaffold_executor(output)

    print(f"Created {args.kind} starter at {output}")


if __name__ == "__main__":
    main()
